export const SET_ACTION_PROGRESS = 'SET_ACTION_PROGRESS'
export const RESET_ACTION_PROGRESS = 'RESET_ACTION_PROGRESS'

export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR'

export const UNITS_EDIT_CHANGED = 'UNITS_EDIT_CHANGED'
export const FILTER_GET = 'CLAIM_CONDITION_GET'
export const FILTER_MODIFY = 'CLAIM_CONDITION_MODIFY'
export const FILTER_CLEAR = 'CLAIM_CONDITION_CLEAR'
export const FILTER_LIST_SCROLL = 'FILTER_LIST_SCROLL'
export const FILTER_SET_DO_NOT_UPDATE = 'FILTER_SET_DO_NOT_UPDATE'

export const CLAIMS_PAGE_CHANGE = 'CLAIMS_PAGE_CHANGE'
export const CLAIMS_FILTER_CHANGE = 'CLAIMS_FILTER_CHANGE'
export const CLAIMS_SORT_CHANGE = 'CLAIMS_SORT_CHANGE'
export const CLAIMS_SORT_ORDER_CHANGE = 'CLAIMS_SORTORD_CHANGE'
export const CLAIMS_START_RECORD_REQUEST = 'CLAIMS_START_RECORD_REQUEST'
export const CLAIMS_SET_DO_NOT_UPDATE = 'CLAIMS_SET_DO_NOT_UPDATE'
export const CLAIMS_LIST_SCROLL = 'CLAIMS_LIST_SCROLL'

export const APP_SESSION_RESET = 'APP_SESSION_RESET'
