/**
 * Created by igorgo on 25.06.2017.
 */

export const UNAUTHORIZED = 'SOCKET_UNAUTHORIZED'
export const AUTHORIZED = 'SOCKET_AUTHORIZED'
export const AUTH_ERROR = 'SOCKET_AUTH_ERROR'
export const SESSION_VALIDATED = 'SOCKET_SESSION_VALIDATED'
export const SESSION_NOT_VALID = 'SOCKET_SESSION_NOT_VALID'

export const ORA_EXEC_ERROR = 'SOCKET_ORA_EXEC_ERROR'

export const SET_CUR_RELEASES = 'SOCKET_SET_CUR_RELEASES'
export const USER_DATA_LOADED = 'SOCKET_USER_DATA_LOADED'
export const CLAIM_CONDITIONS_LIST = 'SOCKET_CLAIM_CONDITIONS_LIST'
export const CLAIM_LIST = 'SOCKET_CLAIM_LIST'
