/**
 * Created by igorgo on 25.06.2017.
 */

export const UNAUTHORIZED = 'SOCKET_UNAUTHORIZED'
export const AUTHORIZED = 'SOCKET_AUTHORIZED'
export const AUTH_ERROR = 'SOCKET_AUTH_ERROR'
export const SESSION_VALIDATED = 'SOCKET_SESSION_VALIDATED'
export const SESSION_NOT_VALID = 'SOCKET_SESSION_NOT_VALID'

export const ORA_EXEC_ERROR = 'SOCKET_ORA_EXEC_ERROR'

export const USER_DATA_LOADED = 'SOCKET_USER_DATA_LOADED'
export const SOCKET_ALL_UNITNAMES_LOADED = 'SOCKET_ALL_UNITNAMES_LOADED'
export const SOCKET_ALL_APPNAMES_LOADED = 'SOCKET_ALL_APPNAMES_LOADED'

export const SET_CUR_RELEASES = 'SOCKET_SET_CUR_RELEASES'
export const CLAIM_CONDITIONS_LIST = 'SOCKET_CLAIM_CONDITIONS_LIST'
export const CLAIM_CONDITION_GOT = 'SOCKET_CLAIM_CONDITION_GOT'
export const CLAIM_CONDITION_GET = 'CLAIM_CONDITION_GET'
export const CLAIM_CONDITION_MODIFY = 'CLAIM_CONDITION_MODIFY'
export const CLAIMS_FILTER_CHANGE = 'CLAIMS_FILTER_CHANGE'
export const CLAIMS_PAGE_CHANGE = 'CLAIMS_PAGE_CHANGE'
export const CLAIMS_SORT_CHANGE = 'CLAIMS_SORT_CHANGE'
export const CLAIMS_SORT_ORDER_CHANGE = 'CLAIMS_SORTORD_CHANGE'
export const CLAIMS_LIMIT_CHANGE = 'CLAIMS_LIMIT_CHANGE'
export const CLAIM_LIST = 'SOCKET_CLAIM_LIST'
